#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3nm_behav_qonly_t10_0
#SBATCH --partition=h200,h100,l40s,a100
#SBATCH --gres=gpu:1
#SBATCH --mem=96G
#SBATCH --cpus-per-task=8
#SBATCH --time=2:30:00
#SBATCH --output=/weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_nemo/logs/s3nm_behav_qonly_t10_0-%j.out

set -euo pipefail

# Source conda's profile script directly, NOT ~/.bashrc. A non-interactive shell
# -- which is what SLURM gives a batch script -- returns early from ~/.bashrc, so
# the `conda` shell function is never defined and `conda activate` dies with
# "Run 'conda init' before 'conda activate'". This is the incantation the
# existing jobs use (jobs/qa_pairs_train.sh:22).
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache

python scripts/run_experiment.py experiments/simplex3_nemo/behavioral_qonly_t10_shard0.yaml --steps build extract --taxonomy behavioral
