#!/bin/bash
# Smoke tests 1b-5 for the OLMo-2-0425-1B-Instruct suite. Chained afterok on the
# prefetch job, since every stage past 1b needs the weights on disk.
#
# NOT generated by gen_simplex3.py: this runs once per new base model, before the
# suite is submitted, and is deliberately not part of the standing job graph.
# submit_all.sh does not reference it, and should not.
#
# --expect-lora-params is not passed: the count (4,194,304) lives in the OLMO2
# profile, which is where a claim about a checkpoint belongs.
#
# Run this one FIRST of the two new suites. At 1B it surfaces any problem shared
# with the nemo suite in minutes rather than in a 12B model's wall.
#
# The --output directory must exist BEFORE submitting this or 00_prefetch.sh.
# submit_all.sh mkdir -p's it, but both of these run ahead of submit_all by
# design, and SLURM fails a job whose output path does not resolve with exit 53
# and no log file at all -- which looks exactly like nothing having happened:
#
#   mkdir -p /weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_olmo2/logs
#SBATCH --job-name=s3o2_smoke
#SBATCH --partition=h200,h100,l40s,a100
#SBATCH --gres=gpu:1
#SBATCH --mem=80G
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --output=/weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_olmo2/logs/s3o2_smoke-%j.out

set -euo pipefail

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache
export HF_DATASETS_OFFLINE=1

nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

python scripts/smoke_base_model.py experiments/simplex3_olmo2/train_shard0.yaml
