#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py --qmix --suite ... -- do not edit by hand.
#
# The QMIX tree: 150 query sets x 3 levels = 450 jobs, over ONE fixed
# adapter fleet. Nothing here trains, so there are no dependencies at all --
# every job below is independent and the stages are ordered by what is worth
# spending the queue on first, not by what must finish before what.
#
# THIS SUBMITS 450 JOBS. Read the cost note before running it whole:
#   - 150 sampled behavioral jobs at ~45 min each is ~112 GPU-h, ~85% of the bill
#   - the greedy and functional stages together are ~25 GPU-h
# Under a 16-GPU cap the whole thing is ~8-9 h of wall clock.
#
# Levers, both without touching a config: run one stage at a time by copying the
# loop you want, or run one arm first --
#   for f in 05_behavioral_qmix_yahoo*_dolly*.sh; do sbatch "$f"; done
#
# sbatch on this cluster refuses without --comment=accept_cost, and the gate
# quotes the REQUESTED wall rather than elapsed time. It is added by hand at
# submit time and is deliberately not baked in here.
#
# CHECK THE QUEUE FIRST -- the partition ordering and the walls were chosen
# against a snapshot of free capacity, and a snapshot written into a config is
# stale by the time it runs:
#
#     sinfo -o "%P %a %D %t %G"
#     squeue --states=PD -o "%P %R" | sort | uniq -c

set -euo pipefail
cd "$(dirname "$0")"
mkdir -p /weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_qmix_olmo2/logs

sb() { sbatch --parsable "$@"; }

for f in 05_behavioral_*.sh; do
  J=$(sb "$f"); echo "behav  ${f%.sh}   $J"
done

for f in 08_greedy_*.sh; do
  J=$(sb "$f"); echo "greedy ${f%.sh}   $J"
done

for f in 04_functional_*.sh; do
  J=$(sb "$f"); echo "func   ${f%.sh}   $J"
done

echo
echo "Submitted. Watch with: squeue -u $USER -o '%.10i %.14j %.9P %.2t %.10M %R'"
