#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3do2_prefetch
#SBATCH --partition=med
#SBATCH --mem=32G
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --output=/weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_dolly_olmo2/logs/s3do2_prefetch-%j.out

set -euo pipefail

# Source conda's profile script directly, NOT ~/.bashrc. A non-interactive shell
# -- which is what SLURM gives a batch script -- returns early from ~/.bashrc, so
# the `conda` shell function is never defined and `conda activate` dies with
# "Run 'conda init' before 'conda activate'". This is the incantation the
# existing jobs use (jobs/qa_pairs_train.sh:22).
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache

python -c "
from huggingface_hub import snapshot_download
p = snapshot_download('allenai/OLMo-2-0425-1B-Instruct', allow_patterns=['*.json','*.safetensors','*.model','tokenizer*','*.jinja','merges.txt'])
print('cached at', p)
"
