#!/bin/bash
# Smoke tests 1b-5 for the Qwen suite. Chained afterok on the prefetch job, since
# every stage needs the weights on disk.
#
# NOT generated by gen_simplex3.py: this runs once per new base model, before the
# suite is submitted, and is deliberately not part of the standing job graph.
#SBATCH --job-name=s3q_smoke
#SBATCH --partition=h100,h200,a100,l40s
#SBATCH --gres=gpu:1
#SBATCH --mem=96G
#SBATCH --cpus-per-task=8
#SBATCH --time=1:30:00
#SBATCH --output=/weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3_qwen/logs/s3q_smoke-%j.out

set -euo pipefail

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache
export HF_DATASETS_OFFLINE=1

nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

python scripts/smoke_base_model.py experiments/simplex3_qwen/train_shard0.yaml
