#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#
# Submits the whole experiment with afterok dependencies.
#
# CHECK THE QUEUE FIRST. The partition ordering and every wall in these scripts
# were chosen against a specific snapshot of free capacity, and a snapshot written
# into a config is stale by the time it runs:
#
#     sinfo -o "%P %a %D %t %G"
#     squeue --states=PD -o "%P %R" | sort | uniq -c
#     sinfo -T                      # migration reservations
#
# Then confirm the prefetch and build jobs actually START before trusting the rest
# of the chain -- everything downstream is afterok on them.

set -euo pipefail
cd "$(dirname "$0")"
mkdir -p /weka/scratch/cpriebe1/MO/model-taxonomy/results/simplex3_qwen/logs

sb() { sbatch --parsable "$@"; }

PREFETCH=$(sb 00_prefetch.sh)
echo "prefetch      $PREFETCH"

# No build or embed jobs: dataset embeddings are model-free (DatasetEmbeddingCache
# is keyed on recipe and embedder, never on the model), so this suite reuses the
# 640 cached centroids. Every job below runs `--steps build ...` and writes the
# handful of recipes it needs itself.

TRAIN=""
for i in 0 1 2 3; do
  J=$(sb --dependency=afterok:$PREFETCH 03_train_shard$i.sh)
  TRAIN="$TRAIN:$J"
  echo "train   $i     $J"
done
TRAIN=${TRAIN#:}

# Extraction depends only on training, so every extraction job is eligible at
# once and the queue orders them.
J=$(sb --dependency=afterok:$TRAIN 04_functional_qonly.sh); echo "func    qonly     $J"
for i in 0 1 2 3 4 5 6 7; do
  J=$(sb --dependency=afterok:$TRAIN 05_behavioral_qonly_shard$i.sh)
  echo "behav   qonly$i    $J"
done

# Greedy: the deterministic control, one job per query set. Its own cache entries
# (GREEDY_SAMPLING nulls the sampling fields), so it cannot collide with the
# R=16 runs over the same adapters and draw.
for q in qonly; do
  J=$(sb --dependency=afterok:$TRAIN 08_greedy_$q.sh)
  echo "greedy  $q     $J"
done

echo
echo "Submitted. Watch with: squeue -u $USER -o '%.10i %.14j %.9P %.2t %.10M %R'"
