"""Split the greedy pool config into strided shards, with a job script each.

The generator sizes the greedy job for a 16-adapter suite and leaves it
unsharded (gen_simplex3.py:811), which is why the 1004-adapter pool run was cut
at 327.  Sharding is strided -- ``names[i::shards]`` -- exactly as the generator
shards training and behavioral, so every shard touches the whole simplex and no
shard is a contiguous slice of sorted adapter names.
"""
import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
#: The generator's own greedy config, read not copied: it is the authority on
#: the query set, prompt format and adapter list, and a second copy of that
#: would drift from it silently.  Only ``name`` and ``extraction.models`` differ
#: in what this writes out.
SRC = ROOT / 'experiments' / 'simplex3_pool_olmo2_pool' / 'greedy_qonly.yaml'
EXP_OUT = ROOT / 'experiments' / 'simplex_collection_size_greedy'
JOB_OUT = ROOT / 'jobs' / 'simplex_collection_size_greedy'
SHARDS = 8

cfg = yaml.safe_load(SRC.read_text())
models = cfg['extraction']['models']
print("adapters in config:", len(models))

EXP_OUT.mkdir(parents=True, exist_ok=True)
JOB_OUT.mkdir(parents=True, exist_ok=True)

JOB = """#!/bin/bash
# Greedy (deterministic, R=1) behavioral draw, shard {i} of {n}: {k} adapters.
#
# Generated by a one-off splitter for figures/simplex_collection_size; NOT by
# scripts/gen_simplex3.py, which sizes the greedy job for a 16-adapter suite and
# leaves it unsharded (gen_simplex3.py:811).  That is why the 1004-adapter pool
# run (job 08) was cut at 327 of 1015 in sorted adapter order, leaving a slice
# that is all low-g1 and useless as a sample of the simplex.
#
# Strided shard: adapters[{i}::{n}], so this shard spans the whole simplex.
# Extraction skips adapters already in the shared cache, so the ~327 already
# done cost only a cache probe here.
#SBATCH --job-name=scs_greedy_s{i}
#SBATCH --partition=h200,h100,l40s,a100
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=8
#SBATCH --time=2:30:00
#SBATCH --output={logs}/scs_greedy_shard{i}-%j.out

set -euo pipefail

# Source conda's profile script directly, NOT ~/.bashrc: a non-interactive shell
# returns early from ~/.bashrc, so the `conda` function is never defined.
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache

python scripts/run_experiment.py \\
    {yaml} \\
    --steps build extract --taxonomy behavioral
"""

logs = cfg['output_dir'] + '/logs'
for i in range(SHARDS):
    part = models[i::SHARDS]
    c = copy.deepcopy(cfg)
    c['name'] = 'simplex_collection_greedy_shard%d' % i
    c['extraction']['models'] = part
    yp = EXP_OUT / ('shard%d.yaml' % i)
    yp.write_text(yaml.safe_dump(c, sort_keys=False, width=10**6))
    jp = JOB_OUT / ('shard%d.sh' % i)
    jp.write_text(JOB.format(i=i, n=SHARDS, k=len(part), yaml=yp, logs=logs))
    jp.chmod(0o755)
    print("shard %d: %4d adapters -> %s" % (i, len(part), jp.name))
