#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3_prefetch
#SBATCH --partition=cpu
#SBATCH --mem=32G
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --output=/weka/scratch/cpriebe1/MO/model-taxonomy/results/simplex3/logs/s3_prefetch-%j.out

set -euo pipefail
source ~/.bashrc
conda activate taxonomy-env
cd /weka/scratch/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/home/mohata1/scratchcpriebe1/MO/huggingface_cache

python -c "
from huggingface_hub import snapshot_download
p = snapshot_download('meta-llama/Llama-3.1-8B', allow_patterns=['*.json','*.safetensors','*.model','tokenizer*'])
print('cached at', p)
"
