#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3_build
#SBATCH --partition=cpu
#SBATCH --mem=32G
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --output=/weka/scratch/jhu/cpriebe1/MO/model-taxonomy/results/simplex3/logs/s3_build-%j.out

set -euo pipefail

# Source conda's profile script directly, NOT ~/.bashrc. A non-interactive shell
# -- which is what SLURM gives a batch script -- returns early from ~/.bashrc, so
# the `conda` shell function is never defined and `conda activate` dies with
# "Run 'conda init' before 'conda activate'". This is the incantation the
# existing jobs use (jobs/qa_pairs_train.sh:22).
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate taxonomy-env
cd /weka/scratch/jhu/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/scratch/jhu/cpriebe1/MO/huggingface_cache

python scripts/run_experiment.py experiments/simplex3/sweep_s00.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s01.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s02.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s03.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s04.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s05.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s06.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s07.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s08.yaml --steps build
python scripts/run_experiment.py experiments/simplex3/sweep_s09.yaml --steps build
