#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3_build_s05
#SBATCH --partition=cpu
#SBATCH --mem=96G
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --output=/weka/scratch/cpriebe1/MO/model-taxonomy/results/simplex3/logs/s3_build_s05-%j.out

set -euo pipefail
source ~/.bashrc
conda activate taxonomy-env
cd /weka/scratch/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/home/mohata1/scratchcpriebe1/MO/huggingface_cache

python scripts/build_datasets.py experiments/simplex3/sweep_s05.yaml
