#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#SBATCH --job-name=s3_embed_s06
#SBATCH --partition=nvl,h100,l40s,a100
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=8
#SBATCH --time=2:00:00
#SBATCH --output=/weka/scratch/cpriebe1/MO/model-taxonomy/results/simplex3/logs/s3_embed_s06-%j.out

set -euo pipefail
source ~/.bashrc
conda activate taxonomy-env
cd /weka/scratch/cpriebe1/MO/model-taxonomy

export TOKENIZERS_PARALLELISM=false
export HF_HOME=/weka/home/mohata1/scratchcpriebe1/MO/huggingface_cache

python scripts/run_experiment.py experiments/simplex3/sweep_s06.yaml --steps build extract --taxonomy dataset_embedding
