#!/bin/bash
# GENERATED BY scripts/gen_simplex3.py -- do not edit by hand.
#
# Submits the whole experiment with afterok dependencies.
#
# CHECK THE QUEUE FIRST. The partition ordering and every wall in these scripts
# were chosen against a specific snapshot of free capacity, and a snapshot written
# into a config is stale by the time it runs:
#
#     sinfo -o "%P %a %D %t %G"
#     squeue --states=PD -o "%P %R" | sort | uniq -c
#     sinfo -T                      # migration reservations
#
# Then confirm the prefetch and build jobs actually START before trusting the rest
# of the chain -- everything downstream is afterok on them.

set -euo pipefail
cd "$(dirname "$0")"
mkdir -p /weka/scratch/cpriebe1/MO/model-taxonomy/results/simplex3/logs

sb() { sbatch --parsable "$@"; }

PREFETCH=$(sb 00_prefetch.sh)
echo "prefetch      $PREFETCH"

# One cheap CPU job: it writes 640 recipe blocks and nothing else, so it is a
# fail-fast gate rather than the sampling work. Draws are materialised on demand
# by the sample cache during embedding.
BUILD=$(sb 01_build.sh)
echo "build         $BUILD"

for s in 00 01 02 03 04 05 06 07 08 09; do
  J=$(sb --dependency=afterok:$BUILD 02_embed_s$s.sh)
  echo "embed   s$s   $J"
done

TRAIN=""
for i in 0 1 2 3; do
  J=$(sb --dependency=afterok:$PREFETCH:$BUILD 03_train_shard$i.sh)
  TRAIN="$TRAIN:$J"
  echo "train   $i     $J"
done
TRAIN=${TRAIN#:}

# Extraction depends only on training, so every extraction job is eligible at
# once and the queue orders them.
J=$(sb --dependency=afterok:$TRAIN 04_functional_a.sh); echo "func    a     $J"
for i in 0 1 2 3 4 5 6 7; do
  J=$(sb --dependency=afterok:$TRAIN 05_behavioral_a_shard$i.sh)
  echo "behav   a$i    $J"
done
J=$(sb --dependency=afterok:$TRAIN 06_functional_b.sh); echo "func    b     $J"
for i in 0 1 2 3 4 5 6 7; do
  J=$(sb --dependency=afterok:$TRAIN 07_behavioral_b_shard$i.sh)
  echo "behav   b$i    $J"
done

# Greedy: the deterministic control, one job per query set. Its own cache entries
# (GREEDY_SAMPLING nulls the sampling fields), so it cannot collide with the
# R=16 runs over the same adapters and draw.
for q in a b; do
  J=$(sb --dependency=afterok:$TRAIN 08_greedy_$q.sh)
  echo "greedy  $q     $J"
done

echo
echo "Submitted. Watch with: squeue -u $USER -o '%.10i %.14j %.9P %.2t %.10M %R'"
